# Sentimen Teks Panjang

Sejauh ini, kami telah membatasi panjang teks yang dimasukkan ke dalam model kami. Bert khususnya dibatasi untuk mengkonsumsi 512 token per sampel. Untuk banyak kasus penggunaan, ini kemungkinan besar bukan masalah - tetapi dalam beberapa kasus bisa saja.

Jika kita mengambil contoh postingan Reddit di subreddit /r/investing, banyak postingan yang lebih penting adalah DD (due-diligence), yang seringkali terdiri dari penyelaman mendalam tentang mengapa penulis menganggap saham adalah investasi yang bagus atau tidak. Pada potongan teks yang lebih panjang ini, sentimen sebenarnya dari penulis mungkin tidak jelas dari 512 token pertama. Kita perlu mempertimbangkan posting lengkap.

Sebelum bekerja melalui logika yang memungkinkan kita untuk mempertimbangkan posting lengkap, mari impor dan tentukan semua yang kita butuhkan untuk membuat prediksi pada satu potongan teks (menggunakan sebagian besar dari apa yang kita bahas di bagian terakhir).

In [1]:
from transformers import BertForSequenceClassification, BertTokenizer
import torch

Dengan menggunakan tanda "**" tokens di depan argumen, argumen yang diberikan dapat diinterpretasikan sebagai sebuah "dictionary" atau kumpulan pasangan key-value.

In [12]:
# initialize our model and tokenizer

tokenizer = BertTokenizer.from_pretrained("ProsusAI/finbert")
model = BertForSequenceClassification.from_pretrained("ProsusAI/finbert")

# and we will place the processing of our input text into a function for easier prediction later

def sentiment(tokens):
    # get output logits from the model
    output = model(**tokens)
    
    # output = [ 0.5, -1.2, 2.1 ] => example
        
    # convert to probabilities
    probs = torch.nn.functional.softmax(output[0], dim=-1)
    
    # we will return the probability tensor (we will not need argmax until later)
    return probs

In [13]:
txt = """
I would like to get your all  thoughts on the bond yield increase this week.  I am not worried about the market downturn but the sudden increase in yields. On 2/16 the 10 year bonds yields increased by almost  9 percent and on 2/19 the yield increased by almost 5 percent.

Key Points from the CNBC Article:

* **The “taper tantrum” in 2013 was a sudden spike in Treasury yields due to market panic after the Federal Reserve announced that it would begin tapering its quantitative easing program.**
* **Major central banks around the world have cut interest rates to historic lows and launched unprecedented quantities of asset purchases in a bid to shore up the economy throughout the pandemic.**
* **However, the recent rise in yields suggests that some investors are starting to anticipate a tightening of policy sooner than anticipated to accommodate a potential rise in inflation.**

The recent rise in bond yields and U.S. inflation expectations has some investors wary that a repeat of the 2013 “taper tantrum” could be on the horizon.

The benchmark U.S. 10-year Treasury note climbed above 1.3% for the first time since February 2020 earlier this week, while the 30-year bond also hit its highest level for a year. Yields move inversely to bond prices.

Yields tend to rise in lockstep with inflation expectations, which have reached their highest levels in a decade in the U.S., powered by increased prospects of a large fiscal stimulus package, progress on vaccine rollouts and pent-up consumer demand.

The “taper tantrum” in 2013 was a sudden spike in Treasury yields due to market panic after the Federal Reserve announced that it would begin tapering its quantitative easing program.

Major central banks around the world have cut interest rates to historic lows and launched unprecedented quantities of asset purchases in a bid to shore up the economy throughout the pandemic. The Fed and others have maintained supportive tones in recent policy meetings, vowing to keep financial conditions loose as the global economy looks to emerge from the Covid-19 pandemic.

However, the recent rise in yields suggests that some investors are starting to anticipate a tightening of policy sooner than anticipated to accommodate a potential rise in inflation.

With central bank support removed, bonds usually fall in price which sends yields higher. This can also spill over into stock markets as higher interest rates means more debt servicing for firms, causing traders to reassess the investing environment.

“The supportive stance from policymakers will likely remain in place until the vaccines have paved a way to some return to normality,” said Shane Balkham, chief investment officer at Beaufort Investment, in a research note this week.

“However, there will be a risk of another ‘taper tantrum’ similar to the one we witnessed in 2013, and this is our main focus for 2021,” Balkham projected, should policymakers begin to unwind this stimulus.

Long-term bond yields in Japan and Europe followed U.S. Treasurys higher toward the end of the week as bondholders shifted their portfolios.

“The fear is that these assets are priced to perfection when the ECB and Fed might eventually taper,” said Sebastien Galy, senior macro strategist at Nordea Asset Management, in a research note entitled “Little taper tantrum.”

“The odds of tapering are helped in the United States by better retail sales after four months of disappointment and the expectation of large issuance from the $1.9 trillion fiscal package.”

Galy suggested the Fed would likely extend the duration on its asset purchases, moderating the upward momentum in inflation.

“Equity markets have reacted negatively to higher yield as it offers an alternative to the dividend yield and a higher discount to long-term cash flows, making them focus more on medium-term growth such as cyclicals” he said. Cyclicals are stocks whose performance tends to align with economic cycles.

Galy expects this process to be more marked in the second half of the year when economic growth picks up, increasing the potential for tapering.

## Tapering in the U.S., but not Europe

Allianz CEO Oliver Bäte told CNBC on Friday that there was a geographical divergence in how the German insurer is thinking about the prospect of interest rate hikes.

“One is Europe, where we continue to have financial repression, where the ECB continues to buy up to the max in order to minimize spreads between the north and the south — the strong balance sheets and the weak ones — and at some point somebody will have to pay the price for that, but in the short term I don’t see any spike in interest rates,” Bäte said, adding that the situation is different stateside.

“Because of the massive programs that have happened, the stimulus that is happening, the dollar being the world’s reserve currency, there is clearly a trend to stoke inflation and it is going to come. Again, I don’t know when and how, but the interest rates have been steepening and they should be steepening further.”

## Rising yields a ‘normal feature’

However, not all analysts are convinced that the rise in bond yields is material for markets. In a note Friday, Barclays Head of European Equity Strategy Emmanuel Cau suggested that rising bond yields were overdue, as they had been lagging the improving macroeconomic outlook for the second half of 2021, and said they were a “normal feature” of economic recovery.

“With the key drivers of inflation pointing up, the prospect of even more fiscal stimulus in the U.S. and pent up demand propelled by high excess savings, it seems right for bond yields to catch-up with other more advanced reflation trades,” Cau said, adding that central banks remain “firmly on hold” given the balance of risks.

He argued that the steepening yield curve is “typical at the early stages of the cycle,” and that so long as vaccine rollouts are successful, growth continues to tick upward and central banks remain cautious, reflationary moves across asset classes look “justified” and equities should be able to withstand higher rates.

“Of course, after the strong move of the last few weeks, equities could mark a pause as many sectors that have rallied with yields look overbought, like commodities and banks,” Cau said.

“But at this stage, we think rising yields are more a confirmation of the equity bull market than a threat, so dips should continue to be bought.”
"""

tokens = tokenizer.encode_plus(txt, add_special_tokens=False)
len(tokens['input_ids'])

Token indices sequence length is longer than the specified maximum sequence length for this model (1345 > 512). Running this sequence through the model will result in indexing errors


1345

In [17]:
inputs_ids = tokens['input_ids']
attention_mask = tokens['attention_mask']

In [18]:
# define our starting position (0) and window size (number of tokens in each chunk)
start = 0
window_size = 512

# get the total length of our tokens
total_len = len(inputs_ids)

# initialize condition for our while loop to run
loop = True

# loop through and print out start/end positions
while loop:
    # the end position is simply the start + window_size
    end = start + window_size
    # if the end position is greater than the total length, make this our final iteration
    if end >= total_len:
        loop = False
        # and change our endpoint to the final token position
        end = total_len
        
    print(f"{start=}\n{end=}")
    # we need to move the window to the next 512 tokens
    start = end

start=0
end=512
start=512
end=1024
start=1024
end=1345


In [30]:
# define our starting position (0) and window size (number of tokens in each chunk)
start = 0
window_size = 510 # we take 2 off here so that we can fit in our [CLS] and [SEP] tokens

probs_list = []

# get the total length of our tokens
total_len = len(inputs_ids)

# initialize condition for our while loop to run
loop = True

# loop through and print out start/end positions
while loop:
    # the end position is simply the start + window_size
    end = start + window_size
    # if the end position is greater than the total length, make this our final iteration
    if end >= total_len:
        loop = False
        # and change our endpoint to the final token position
        end = total_len
        
    # (1) extract window from input_ids and attention_mask & add [CLS] and [SEP]

    inputs_ids_chunk = [101] + inputs_ids[start:end] + [102] # 512 len
    attention_mask_chunk = [1] + attention_mask[start:end] + [1]
                
    # (2) add padding upto window_size + 2 (512) tokens
    
    # Output dari baris ini adalah list "inputs_ids_chunk" yang telah diperbarui dan diisi dengan token 0 sebanyak (window_size - len(inputs_ids_chunk)) buah. 
    
    inputs_ids_chunk += [0] * ( window_size - len(inputs_ids_chunk) + 2 )
    attention_mask_chunk += [0] * ( window_size - len(attention_mask_chunk) + 2 )
    
    # (3) format into PyTorch tensors dictionary
    
    # convert [input_ids_chunk] list to tensor
    
    input_dict = {
        'input_ids': torch.Tensor([inputs_ids_chunk]).long(),
        'attention_mask': torch.Tensor([attention_mask_chunk]).int()
    }
    
    # (4) make logits prediction
    
    # SequenceClassifierOutput(loss=None, logits=tensor([[-0.2807,  1.4917, -1.3592]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)
    # akan berisi 3 logits untuk di hitung sebagai probabilitas
    
    output = model(**input_dict)
        
    # (5) calculate softmax and append to list, will be out probabilities
    
    probs = torch.nn.functional.softmax(output[0], dim=-1)
    probs_list.append(probs)
        
    # we need to move the window to the next 512 tokens
    start = end
    
probs_list

[tensor([[0.1384, 0.8145, 0.0471]], grad_fn=<SoftmaxBackward0>),
 tensor([[0.3757, 0.4670, 0.1574]], grad_fn=<SoftmaxBackward0>),
 tensor([[0.7290, 0.2006, 0.0704]], grad_fn=<SoftmaxBackward0>)]

Logits adalah nilai numerik yang dihasilkan oleh output layer dari sebuah model machine learning sebelum dilakukan transformasi ke probabilitas. Logits dapat dianggap sebagai representasi dari kepercayaan model terhadap suatu kelas atau kategori.

Dalam konteks klasifikasi, misalnya, setiap kelas yang mungkin memiliki sebuah skor logits yang dihitung oleh model. Skor ini kemudian digunakan untuk menentukan probabilitas masing-masing kelas menggunakan fungsi softmax. Semakin tinggi skor logits untuk sebuah kelas, semakin besar pula probabilitas bahwa input tersebut masuk ke kelas tersebut.

Logits dapat digunakan sebagai output dari model ketika kita hanya perlu membandingkan skor relatif antara kelas-kelas yang mungkin, atau ketika kita ingin mengambil keputusan berdasarkan skor tertinggi tanpa memperhatikan seberapa besar selisih antara skor yang terbesar dan skor kedua terbesar. Namun, untuk keperluan interpretasi dan visualisasi, biasanya lebih mudah untuk menggunakan probabilitas.

Each section has been assign varying levels of sentiment. The first and section sections both score negatively (index 1) and the final sections scores positively (index 0). To calculate the average sentiment across the full text, we will merge these tensors using the stack method:

In [31]:
stacks = torch.stack(probs_list)
stacks

tensor([[[0.1384, 0.8145, 0.0471]],

        [[0.3757, 0.4670, 0.1574]],

        [[0.7290, 0.2006, 0.0704]]], grad_fn=<StackBackward0>)

In [32]:
stacks.shape

torch.Size([3, 1, 3])

In [35]:
stacks.shape[0], stacks.shape[2]

(3, 3)

In [36]:
stacks.resize_(stacks.shape[0], stacks.shape[2])

RuntimeError: cannot resize variables that require grad

When we try to resize our tensor, we will receive this RuntimeError telling us that we cannot resize variables that require grad. What this is referring to is the gradient updates of our model tensors during training. PyTorch cannot calculate gradients for tensors that have been reshaped. Fortunately, we don't actually want to use this tensor during any training, so we can use the torch.no_grad() namespace to tell PyTorch that we do not want to calculate any gradients.

In [37]:
with torch.no_grad():
    # we must include our stacks operation in here too
    stacks = torch.stack(probs_list)
    # now resize
    stacks = stacks.resize_(stacks.shape[0], stacks.shape[2])
    # finally, we can calculate the mean value for each sentiment class
    mean = stacks.mean(dim=0)
    
mean

tensor([0.4144, 0.4940, 0.0916])

In [38]:
torch.argmax(mean).item()

1